# Generated by Django 5.2.4 on 2025-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='backstage/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Видео (ссылка)')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показать на главной?')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.TextField(verbose_name='Описание')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показать на главной?')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
