# Generated by Django 5.2.4 on 2025-07-22 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
