# Generated by Django 5.2.4 on 2025-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_backstage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Изображение'),
        ),
    ]
