# Generated by Django 5.2.4 on 2025-07-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstage',
            name='subtitle',
            field=models.CharField(default='', verbose_name='Подзаголовок'),
        ),
    ]
