# Generated by Django 5.2.4 on 2025-08-01 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_backstage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
