# Generated by Django 5.2.4 on 2025-08-01 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_backstage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='backstage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
