# Generated by Django 5.2.4 on 2025-08-01 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_backstage_uuid_alter_backstage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
