# Generated by Django 5.2.4 on 2025-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_backstage_uuid_alter_backstage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstage',
            name='video_embed',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
