# Generated by Django 5.2.4 on 2025-08-05 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_backstage_video_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на покупку билета'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
