# Generated by Django 5.2.4 on 2025-08-05 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_ticket_url_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast_photos/', verbose_name='Фото')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('theater', models.CharField(blank=True, max_length=255, verbose_name='Театр / Труппа')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('roles', models.TextField(blank=True, verbose_name='Основные партии / роли')),
                ('awards', models.TextField(blank=True, verbose_name='Награды и звания')),
                ('activity_period', models.CharField(blank=True, max_length=100, verbose_name='Период активности')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Город / Местоположение')),
                ('instagram', models.URLField(blank=True, max_length=255, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Персональный сайт')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Языки')),
                ('video_links', models.TextField(blank=True, verbose_name='Видео выступлений (ссылки)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Артист балета',
                'verbose_name_plural': 'Артисты балета',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('image', models.ImageField(blank=True, null=True, upload_to='creatives/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Творческий специалист',
                'verbose_name_plural': 'Творческая команда',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Постановка', 'verbose_name_plural': 'Постановки'},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='EventCastRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, verbose_name='Партию / Роль')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to='website.cast')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_roles', to='website.event')),
            ],
            options={
                'verbose_name': 'Артист в постановке',
                'verbose_name_plural': 'Артисты в постановке',
                'unique_together': {('event', 'cast', 'role')},
            },
        ),
        migrations.CreateModel(
            name='EventCreativeRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('choreographer', 'Хореограф'), ('director', 'Режиссёр'), ('composer', 'Композитор'), ('set_designer', 'Художник-постановщик'), ('costume_designer', 'Художник по костюмам'), ('lighting_designer', 'Художник по свету'), ('conductor', 'Дирижёр'), ('dramaturg', 'Драматург')], max_length=50, verbose_name='Роль в постановке')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to='website.creative')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_roles', to='website.event')),
            ],
            options={
                'verbose_name': 'Творец в постановке',
                'verbose_name_plural': 'Творцы в постановке',
                'unique_together': {('event', 'creative', 'role')},
            },
        ),
    ]
