# Generated by Django 5.2.4 on 2025-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_cast_creative_alter_event_options_event_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
