# Generated by Django 5.2.4 on 2025-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_event_age_limit_event_duration_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='image',
            field=models.ImageField(blank=True, default='defaults/blank-profile-picture-973460_1280.png', null=True, upload_to='creatives/', verbose_name='Фото'),
        ),
    ]
