# Generated by Django 5.2.4 on 2025-08-07 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_creative_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backstage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='backstage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
